-- 项目环评和验收统计
-- HW_BUILD_PROJECT
-- HW_PROJECT_EIA
-- HW_PROJECT_ACCEPTANCE

SELECT
	DATE_FORMAT(a.REPLY_ACC_TIME, '%Y-%m'),
	count(1)
FROM
	HW_PROJECT_ACCEPTANCE a
WHERE
	a.IS_ACC_LICENSE = 1
GROUP BY
	DATE_FORMAT(a.REPLY_ACC_TIME, '%Y-%m')
ORDER BY
	DATE_FORMAT(a.REPLY_ACC_TIME, '%Y-%m');

SELECT
	p.id,
	p.IS_ACCEPTANCE,
	p.REPLY_ACC_TIME,
	a.id
FROM
	HW_PROJECT_ACCEPTANCE a,
	HW_BUILD_PROJECT p
WHERE
	a.PROJECT_ID = p.id
AND a.IS_ACC_LICENSE = 1
AND DATE_FORMAT(a.REPLY_ACC_TIME, '%Y-%m') = '2017-01';

UPDATE HW_BUILD_PROJECT bp
SET bp.IS_ACCEPTANCE = '1',
 bp.REPLY_ACC_TIME = '2017-01-06 00:00:00'
WHERE
	bp.id IN (
		'f3e64f811895432cbe7f5b5db6c5ce31',
		'036a7423b58e40a79975866b4acb72d0'
	);

